# Base image, assuming you're using Python 3.9
FROM python:3.9-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the source tree and model weights into the container
COPY . /app
RUN mkdir -p /app/.cxas/weights && \
    cp /app/cxas/weights/UNet_resnet50_default.pth /app/.cxas/weights/UNet_ResNet50_default.pth

ENV CXAS_PATH=/app/

# Install system-level dependencies (including libGL and libglib)
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    libjpeg-dev \
    zlib1g-dev \
    libpng-dev \
    libgl1 \
    libglib2.0-0 && \
    rm -rf /var/lib/apt/lists/*

# Install Python dependencies
RUN pip install --upgrade pip && \
    pip install setuptools wheel && \
    pip install --no-cache-dir --index-url https://download.pytorch.org/whl/cpu torch torchvision && \
    pip install --no-cache-dir -e .

# # Optional: if you want to provide a default entry point for your CLI tool
ENTRYPOINT ["cxas"]
